### ISSUE TITLE
Westworld Command Center

### ISSUE THREAD

**Issue by achardon** [learn-co-curriculum/react-hooks-practice-westworld-command-center#1]
### Canvas Link

https://learning.flatironschool.com/courses/4331/assignments/135109?module_item_id=280794

### Concern

This is really minor, but when the hosts appear in the various areas, the formatting makes them appear in one vertical line, instead of wrapping so they don't show up outside of the borders of that specific area. This is the case even with the area limits in place. It says in this lesson that formatting/styling is already set, so I just wanted to bring this to your attention. I am not aware of any className that I should be using but am not. I am hoping you can see this with the screenshot below. I'm assuming it's an easy fix but my CSS skills are not quite up to par to know exactly what should be changed. 

### Additional Context

<img width="1345" alt="Screen Shot 2021-11-18 at 5 13 35 PM" src="https://user-images.githubusercontent.com/63176194/142505401-95ff04ad-00f2-4630-b5ea-810c468a672d.png">

**Comment by graciemcguire** [comment]
Hey @achardon !

It looks like the the `display: flex` property isn't being rendered here. Looking at the dev tools, it looks like that property is coming from the `HostList` component that's a child of the `Area` component. 
<img width="807" alt="Screen Shot 2021-11-30 at 12 56 48 PM" src="https://user-images.githubusercontent.com/40892567/144101886-c559fb4b-3e86-4968-aa6b-7dcaed18448e.png">

Make sure your `HostList` component code is similar to:

```jsx

import React from "react";
import Host from "./Host";
import { Card } from "semantic-ui-react";

function HostList({ hosts, onHostClick }) {
  const hostList = hosts.map((host) => (
    <Host key={host.id} host={host} onHostClick={onHostClick} />
  ));

  return <Card.Group itemsPerRow={6}>{hostList}</Card.Group>;
}

export default HostList;
```

Hopefully this helps! Happy coding!
